/**
 * @license
 * Copyright 2011 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Former goog.module ID: Blockly.blockRendering.PathObject

import type {BlockSvg} from '../../block_svg.js';
import type {RenderedConnection} from '../../rendered_connection.js';
import type {BlockStyle} from '../../theme.js';
import {Coordinate} from '../../utils/coordinate.js';
import * as dom from '../../utils/dom.js';
import type {ConstantProvider} from '../common/constants.js';
import type {IPathObject} from '../common/i_path_object.js';

/**
 * An object that handles creating and setting each of the Canvas elements
 * used by the renderer.
 */
export class PathObject implements IPathObject {
  // These properties are required by the IPathObject interface but are not used in Canvas rendering
  svgPath: any;
  constants: ConstantProvider;
  style: BlockStyle;

  private canvasElement: HTMLCanvasElement;
  private ctx: CanvasRenderingContext2D;
  private pathString: string = '';
  private rootElement: HTMLElement;

  /** Highlight paths associated with connections. */
  private connectionHighlights = new WeakMap<
    RenderedConnection,
    HTMLCanvasElement
  >();

  /** Locations of connection highlights. */
  private highlightOffsets = new WeakMap<RenderedConnection, Coordinate>();

  /**
   * @param root The root HTML element.
   * @param style The style object to use for colouring.
   * @param constants The renderer's constants.
   */
  constructor(
    root: any, // This will be an HTML element, not SVG
    style: BlockStyle,
    constants: ConstantProvider,
  ) {
    this.rootElement = root;
    this.style = style;
    this.constants = constants;

    // Create canvas element
    this.canvasElement = document.createElement('canvas');
    this.ctx = this.canvasElement.getContext('2d')!;

    // Set canvas properties
    this.canvasElement.className = 'blocklyCanvas';
    this.canvasElement.style.position = 'absolute';
    this.canvasElement.style.top = '0';
    this.canvasElement.style.left = '0';

    // Append to root
    this.rootElement.appendChild(this.canvasElement);

    // Add CSS class for canvas rendering
    dom.addClass(this.rootElement, 'blocklyBlockCanvas');

    // Required by IPathObject interface - set to null since we don't use SVG
    this.svgPath = null;
  }

  /**
   * Get the canvas element.
   */
  getCanvas(): HTMLCanvasElement {
    return this.canvasElement;
  }

  /**
   * Set the path generated by the renderer onto the respective Canvas element.
   *
   * @param pathString The path.
   */
  setPath(pathString: string) {
    this.pathString = pathString;

    // Update canvas size if needed
    this.updateCanvasSize_();

    // Render the path
    this.renderPath_();
  }

  /**
   * Update the canvas size based on the block size.
   */
  private updateCanvasSize_() {
    // For simplicity, we'll set a fixed size for now
    // In a real implementation, this should be calculated from the block size
    this.canvasElement.width = 200;
    this.canvasElement.height = 100;
  }

  /**
   * Render the path onto the canvas.
   */
  private renderPath_() {
    if (!this.ctx || !this.pathString) return;

    // Clear canvas
    this.ctx.clearRect(
      0,
      0,
      this.canvasElement.width,
      this.canvasElement.height,
    );

    // Parse and draw the path
    this.parseAndDrawPath_(this.pathString);

    // Apply styling
    this.ctx.fillStyle = this.style.colourPrimary;
    this.ctx.strokeStyle = this.style.colourTertiary;
    this.ctx.lineWidth = 2; // Blockly default stroke width

    this.ctx.fill();
    this.ctx.stroke();
  }

  /**
   * Parse SVG path string and draw it on canvas.
   *
   * @param pathString SVG path string.
   */
  private parseAndDrawPath_(pathString: string) {
    if (!this.ctx) return;

    // Simple path parser - handles basic commands
    const commands = pathString.match(/[a-zA-Z][^a-zA-Z]*/g) || [];

    this.ctx.beginPath();

    let x = 0;
    let y = 0;

    for (const command of commands) {
      const type = command[0];
      const params = command
        .slice(1)
        .trim()
        .split(/[,\s]+/)
        .map((p) => parseFloat(p))
        .filter((p) => !isNaN(p));

      let i = 0;

      while (i < params.length) {
        switch (type.toUpperCase()) {
          case 'M': // Move to
            x = params[i];
            y = params[i + 1];
            this.ctx.moveTo(x, y);
            i += 2;
            break;
          case 'L': // Line to
            x = params[i];
            y = params[i + 1];
            this.ctx.lineTo(x, y);
            i += 2;
            break;
          case 'C': // Cubic Bezier
            this.ctx.bezierCurveTo(
              params[i],
              params[i + 1],
              params[i + 2],
              params[i + 3],
              params[i + 4],
              params[i + 5],
            );
            x = params[i + 4];
            y = params[i + 5];
            i += 6;
            break;
          case 'Q': // Quadratic Bezier
            this.ctx.quadraticCurveTo(
              params[i],
              params[i + 1],
              params[i + 2],
              params[i + 3],
            );
            x = params[i + 2];
            y = params[i + 3];
            i += 4;
            break;
          case 'Z': // Close path
            this.ctx.closePath();
            break;
        }
      }
    }
  }

  /**
   * Flip the Canvas paths in RTL.
   */
  flipRTL() {
    this.canvasElement.style.transform = 'scale(-1, 1)';
    this.canvasElement.style.transformOrigin = 'center';
  }

  /**
   * Apply the stored colours to the block's path, taking into account whether
   * the paths belong to a shadow block.
   *
   * @param block The source block.
   */
  applyColour(_block: BlockSvg) {
    // Colours are applied during rendering
    this.renderPath_();
  }

  /**
   * Set the style.
   *
   * @param blockStyle The block style to use.
   */
  setStyle(blockStyle: BlockStyle) {
    this.style = blockStyle;
    this.renderPath_();
  }

  /**
   * Set whether the block shows a highlight or not.  Block highlighting is
   * often used to visually mark blocks currently being executed.
   *
   * @param enable True if highlighted.
   */
  updateHighlighted(_enable: boolean) {
    if (_enable) {
      dom.addClass(this.rootElement, 'blocklyHighlighted');
    } else {
      dom.removeClass(this.rootElement, 'blocklyHighlighted');
    }
  }

  /**
   * Add or remove styling showing that a block is selected.
   *
   * @param enable True if selection is enabled, false otherwise.
   */
  updateSelected(_enable: boolean) {
    if (_enable) {
      dom.addClass(this.rootElement, 'blocklySelected');
    } else {
      dom.removeClass(this.rootElement, 'blocklySelected');
    }
  }

  /**
   * Add or remove styling showing that a block is dragged over a delete area.
   *
   * @param enable True if the block is being dragged over a delete area, false
   *     otherwise.
   */
  updateDraggingDelete(_enable: boolean) {
    if (_enable) {
      dom.addClass(this.rootElement, 'blocklyDraggingDelete');
    } else {
      dom.removeClass(this.rootElement, 'blocklyDraggingDelete');
    }
  }

  /**
   * Add or remove styling showing that a block is an insertion marker.
   *
   * @param enable True if the block is an insertion marker, false otherwise.
   */
  updateInsertionMarker(_enable: boolean) {
    if (_enable) {
      dom.addClass(this.rootElement, 'blocklyInsertionMarker');
    } else {
      dom.removeClass(this.rootElement, 'blocklyInsertionMarker');
    }
  }

  /**
   * Add or remove styling showing that a block is movable.
   *
   * @param enable True if the block is movable, false otherwise.
   */
  updateMovable(_enable: boolean) {
    if (_enable) {
      dom.addClass(this.rootElement, 'blocklyDraggable');
    } else {
      dom.removeClass(this.rootElement, 'blocklyDraggable');
    }
  }

  /**
   * Updates the look of the block to reflect a shadow state.
   *
   * @param block The source block.
   */
  updateShadow_(_block: BlockSvg) {
    if (_block.isShadow()) {
      dom.addClass(this.rootElement, 'blocklyShadow');
      this.style.colourPrimary = this.style.colourSecondary;
      this.style.colourTertiary = 'none';
      this.renderPath_();
    } else {
      dom.removeClass(this.rootElement, 'blocklyShadow');
      this.renderPath_();
    }
  }

  /**
   * Updates the look of the block to reflect a disabled state.
   *
   * @param block The source block.
   */
  updateDisabled_(_block: BlockSvg) {
    const disabled = !_block.isEnabled() || _block.getInheritedDisabled();
    if (disabled) {
      dom.addClass(this.rootElement, 'blocklyDisabled');
      dom.addClass(this.rootElement, 'blocklyDisabledPattern');
    } else {
      dom.removeClass(this.rootElement, 'blocklyDisabled');
      dom.removeClass(this.rootElement, 'blocklyDisabledPattern');
    }
  }

  /**
   * Set the opacity of the block.
   *
   * @param opacity The opacity value between 0 and 1.
   */
  setOpacity(opacity: number) {
    this.canvasElement.style.opacity = opacity.toString();
  }

  /**
   * Set the cursor style.
   *
   * @param cursor The cursor style.
   */
  updateCursor(_cursor: string) {
    this.canvasElement.style.cursor = _cursor;
  }

  /**
   * Updates the block's UI based on the given block's state.
   *
   * @param block The block to use as a reference for updating the UI.
   */
  updateFromBlock(block: BlockSvg) {
    this.updateShadow_(block);
    this.updateDisabled_(block);
  }

  /**
   * Dispose of all DOM objects owned by this path object.
   */
  dispose() {
    if (this.canvasElement && this.canvasElement.parentElement) {
      this.canvasElement.parentElement.removeChild(this.canvasElement);
    }

    // Dispose of connection highlights - WeakMap doesn't support clear() in older TS versions
    // We'll leave them for garbage collection
  }
}
