/**
 * @license
 * Copyright 2024 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Former goog.module ID: Blockly.threejs.PathObject

import {ConstantProvider} from '../common/constants.js';
import {IPathObject} from '../common/i_path_object.js';
import {BlockStyle} from '../../theme.js';
import * as THREE from 'three';

export class PathObject implements IPathObject {
  svgPath: SVGElement;
  constants: ConstantProvider;
  style: BlockStyle;

  // Three.js objects
  private mesh_: THREE.Mesh | null = null;
  private scene_: THREE.Scene | null = null;
  private material_: THREE.Material | null = null;
  private group_: THREE.Group | null = null;
  private x_: number = 0;
  private y_: number = 0;
  private z_: number = 0;

  // Block dimensions (in 3D units)
  private width_: number = 1;
  private height_: number = 0.5;
  private depth_: number = 0.2;

  /**
   * @param root The root SVG element.
   * @param style The style object to use for colouring.
   * @param constants The renderer's constants.
   */
  constructor(root: SVGElement, style: BlockStyle, constants: ConstantProvider) {
    this.svgPath = root;
    this.style = style;
    this.constants = constants;

    // Initialize Three.js objects
    this.initThreeJs_();
  }

  /**
   * Initialize Three.js scene, camera, renderer, etc.
   */
  private initThreeJs_(): void {
    // Get the container div
    const container = this.svgPath.parentElement?.parentElement;
    if (!container || !(container instanceof HTMLElement)) {
      return;
    }

    // Check if Three.js scene already exists
    let scene = container.querySelector('.blockly-threejs-scene');
    if (!scene) {
      scene = document.createElement('div');
      scene.className = 'blockly-threejs-scene';
      (scene as HTMLElement).style.width = '100%';
      (scene as HTMLElement).style.height = '100%';
      (scene as HTMLElement).style.position = 'absolute';
      (scene as HTMLElement).style.top = '0';
      (scene as HTMLElement).style.left = '0';
      container.appendChild(scene);

      // Create scene
      const threeScene = new THREE.Scene();
      threeScene.background = new THREE.Color(0xf0f0f0);

      // Create camera
      const camera = new THREE.PerspectiveCamera(
        75,
        container.clientWidth / container.clientHeight,
        0.1,
        1000
      );
      camera.position.z = 5;

      // Create renderer
      const renderer = new THREE.WebGLRenderer({antialias: true});
      renderer.setSize(container.clientWidth, container.clientHeight);
      scene.appendChild(renderer.domElement);

      // Create lights
      const ambientLight = new THREE.AmbientLight(0x404040, 0.5);
      threeScene.add(ambientLight);

      const directionalLight = new THREE.DirectionalLight(0xffffff, 0.8);
      directionalLight.position.set(1, 1, 1);
      threeScene.add(directionalLight);

      const directionalLight2 = new THREE.DirectionalLight(0xffffff, 0.3);
      directionalLight2.position.set(-1, -1, 1);
      threeScene.add(directionalLight2);

      // Store references
      (scene as any).threeScene = threeScene;
      (scene as any).threeCamera = camera;
      (scene as any).threeRenderer = renderer;

      // Start animation loop
      const animate = () => {
        requestAnimationFrame(animate);
        renderer.render(threeScene, camera);
      };
      animate();

      this.scene_ = threeScene;
    } else {
      this.scene_ = (scene as any).threeScene;
    }
  }

  /**
   * Set the path generated by the renderer onto the respective SVG element.
   *
   * @param pathString The path.
   */
  setPath(pathString: string): void {
    // Convert SVG path to Three.js geometry
    this.createBlockMesh_(pathString);
    // Update position after creating mesh
    this.updatePosition(this.x_, this.y_);
  }

  /**
   * Update the 3D position of the block.
   *
   * @param x The x coordinate in workspace units.
   * @param y The y coordinate in workspace units.
   */
  updatePosition(x: number, y: number): void {
    this.x_ = x;
    this.y_ = y;

    if (!this.mesh_) {
      return;
    }

    // Convert workspace coordinates to 3D world coordinates
    // Scale factor to convert from workspace units to 3D units
    const scaleFactor = 0.01;
    const zOffset = (this as any).zOffset || 0;

    // Invert y because SVG y increases downward, but Three.js y increases upward
    this.mesh_.position.set(
      x * scaleFactor,
      -y * scaleFactor,
      zOffset
    );
  }

  /**
   * Parse a color value from Blockly style to Three.js color.
   *
   * @param color The color value from Blockly style.
   * @param defaultValue The default color if parsing fails.
   * @returns The parsed color as a number.
   */
  private parseColor_(color: string | number | undefined, defaultValue: number): number {
    if (color === undefined) {
      return defaultValue;
    }
    if (typeof color === 'number') {
      return color;
    }
    const parsed = parseInt(color, 16);
    return isNaN(parsed) ? defaultValue : parsed;
  }

  /**
   * Create a 3D mesh for the block from the SVG path.
   *
   * @param pathString The SVG path string.
   */
  private createBlockMesh_(pathString: string): void {
    if (!this.scene_) {
      return;
    }

    // Remove old mesh if it exists
    if (this.mesh_) {
      this.scene_.remove(this.mesh_);
      this.mesh_.geometry.dispose();
      (this.mesh_.material as THREE.Material).dispose();
      this.mesh_ = null;
    }

    // Create a simple box geometry for demonstration
    // TODO: Convert actual SVG path to 3D geometry based on pathString
    const geometry = new THREE.BoxGeometry(this.width_, this.height_, this.depth_);

    // Create material with block style
    const material = new THREE.MeshPhongMaterial({
      color: this.parseColor_(this.style.colourPrimary, 0x4a90e2),
      emissive: this.parseColor_(this.style.colourSecondary, 0x2c5aa0),
      shininess: 30,
      side: THREE.DoubleSide,
    });
    this.material_ = material;

    // Create mesh
    const mesh = new THREE.Mesh(geometry, material);
    this.mesh_ = mesh;

    // Add to scene
    this.scene_.add(mesh);
  }

  /**
   * Flip the SVG paths in RTL.
   */
  flipRTL(): void {
    // Not implemented yet
  }

  /**
   * Set whether the block shows a highlight or not.
   *
   * @param highlighted True if highlighted.
   */
  updateHighlighted(highlighted: boolean): void {
    if (this.material_) {
      (this.material_ as THREE.MeshPhongMaterial).emissive.setHex(
        highlighted ? 0xffff00 : this.parseColor_(this.style.colourSecondary, 0x2c5aa0)
      );
    }
  }

  /**
   * Set whether the block is selected or not.
   *
   * @param selected True if selected.
   */
  updateSelected(selected: boolean): void {
    if (this.mesh_) {
      this.mesh_.scale.set(selected ? 1.05 : 1, selected ? 1.05 : 1, selected ? 1.1 : 1);
    }
  }

  /**
   * Set whether the block is movable or not.
   *
   * @param movable True if movable.
   */
  updateMovable(movable: boolean): void {
    // Not implemented yet
  }

  /**
   * Set whether the block is editable or not.
   *
   * @param editable True if editable.
   */
  updateEditable(editable: boolean): void {
    // Not implemented yet
  }

  /**
   * Set whether the block is disabled or not.
   *
   * @param disabled True if disabled.
   */
  updateDisabled(disabled: boolean): void {
    if (this.material_) {
      (this.material_ as THREE.MeshPhongMaterial).opacity = disabled ? 0.5 : 1;
      (this.material_ as THREE.MeshPhongMaterial).transparent = disabled;
    }
  }

  /**
   * Set whether the block is an insertion marker or not.
   *
   * @param insertionMarker True if insertion marker.
   */
  updateInsertionMarker(insertionMarker: boolean): void {
    // Not implemented yet
  }

  /**
   * Set whether the block is being dragged over or not.
   *
   * @param hasDragOverlay True if has drag overlay.
   */
  updateDraggingDelete(hasDragOverlay: boolean): void {
    // Not implemented yet
  }
}