/**
 * @license
 * Copyright 2023 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import * as Blockly from './blockly.js';
import * as parser from './script_parser.js';
import * as utilsXml from './utils/xml.js';

declare interface CodeConverter {
  convert(code: string, language: string): Element;
  convertJavaScript(code: string): Element;
  convertPython(code: string): Element;
  convertLua(code: string): Element;
  convertPHP(code: string): Element;
  convertDart(code: string): Element;
  convertASTToXml(ast: any): Element;
}

/**
 * Converts code text from a specified language into Blockly XML using
 * the corresponding parser module.
 */
export const CodeConverter: CodeConverter = {
  convert(code: string, language: string): Element {
    const parserModule = parser[language.toLowerCase() as keyof typeof parser];
    if (!parserModule) {
      throw new Error(`Unsupported language: ${language}`);
    }
    const ast = parserModule.parse(code);
    return CodeConverter.convertASTToXml(ast);
  },

  convertJavaScript(code: string): Element {
    const ast = parser.javascript.parse(code);
    return CodeConverter.convertASTToXml(ast);
  },

  convertPython(code: string): Element {
    const ast = parser.python.parse(code);
    return CodeConverter.convertASTToXml(ast);
  },

  convertLua(code: string): Element {
    const ast = parser.lua.parse(code);
    return CodeConverter.convertASTToXml(ast);
  },

  convertPHP(code: string): Element {
    const ast = parser.php.parse(code);
    return CodeConverter.convertASTToXml(ast);
  },

  convertDart(code: string): Element {
    const ast = parser.dart.parse(code);
    return CodeConverter.convertASTToXml(ast);
  },

  /**
   * Converts an AST (Abstract Syntax Tree) to Blockly XML.
   * This method should be implemented to handle the AST structure
   * generated by the script_parser.
   *
   * @param ast The AST to convert.
   * @returns The Blockly XML representation.
   */
  convertASTToXml(ast: any): Element {
    const xmlDoc = utilsXml.createElement('xml');

    // Example: Handle variable declarations and assignments
    for (const node of ast) {
      if (node.type === 'VariableDeclaration') {
        for (const declarator of node.declarations) {
          if (declarator.type === 'VariableDeclarator' && declarator.init) {
            const block = utilsXml.createElement('block');
            block.setAttribute('type', 'variables_set');

            // Variable name
            const varNameField = utilsXml.createElement('field');
            varNameField.setAttribute('name', 'VAR');
            varNameField.textContent = declarator.id.name;
            block.appendChild(varNameField);

            // Value input
            const valueInput = utilsXml.createElement('value');
            valueInput.setAttribute('name', 'VALUE');

            // Number value (simplified example)
            const numberBlock = utilsXml.createElement('block');
            numberBlock.setAttribute('type', 'math_number');
            const numberField = utilsXml.createElement('field');
            numberField.setAttribute('name', 'NUM');
            numberField.textContent = declarator.init.value;
            numberBlock.appendChild(numberField);

            valueInput.appendChild(numberBlock);
            block.appendChild(valueInput);
            xmlDoc.appendChild(block);
          }
        }
      }
    }

    return xmlDoc;
  },
};

// Register the CodeConverter in the Blockly namespace
// Using Object.assign to avoid TypeScript error
Object.assign(Blockly, {CodeConverter});

/**
 * 检测代码语言
 *
 * @param code 代码字符串
 * @returns 检测到的语言类型
 */
export function detectLanguage(code: string): string {
  // 简单的语言检测逻辑
  if (
    code.includes('var ') ||
    code.includes('let ') ||
    code.includes('const ') ||
    code.includes('function ')
  ) {
    return 'javascript';
  } else if (
    code.includes('def ') ||
    code.includes('class ') ||
    code.includes('import ') ||
    code.includes('print(')
  ) {
    return 'python';
  } else if (
    code.includes('local ') ||
    code.includes('function(') ||
    code.includes('require(')
  ) {
    return 'lua';
  } else if (
    code.includes('<?php') ||
    code.includes('echo ') ||
    code.includes('require_once')
  ) {
    return 'php';
  } else if (
    code.includes('void ') ||
    code.includes('class ') ||
    code.includes('import ') ||
    code.includes('print(')
  ) {
    return 'dart';
  }
  return 'javascript'; // 默认返回JavaScript
}

/**
 * 根据文件扩展名检测语言
 *
 * @param fileName 文件名
 * @returns 检测到的语言类型
 */
export function detectLanguageFromFile(fileName: string): string {
  const ext = fileName.split('.').pop()?.toLowerCase();
  switch (ext) {
    case 'js':
      return 'javascript';
    case 'py':
      return 'python';
    case 'lua':
      return 'lua';
    case 'php':
      return 'php';
    case 'dart':
      return 'dart';
    default:
      return 'javascript';
  }
}
